export const GET_PAGE_VIEWS_LINE_CHART = 'GET_PAGE_VIEWS_LINE_CHART';
export const GET_PAGE_VIEWS_BAR_CHART = 'GET_PAGE_VIEWS_BAR_CHART';
export const GET_PAGE_VIEWS_HEATMAP = 'GET_PAGE_VIEWS_HEATMAP';
export const GET_PIE_CHART_COMPONENTS = 'GET_PIE_CHART_COMPONENTS';
export const GET_SCATTER_PLOT = 'GET_SCATTER_PLOT';

export const GET_HISTOGRAM_DATA = 'GET_HISTOGRAM_DATA';
